(* magic EBNF grammar *)

magic = lvar-ctor*
lvar-ctor = ( <LP> <LVAR> <RP> | <LP> <LVAR> string lvar-init? <RP> )
lvar-init = literal | bounds-literal

bounds-literal = <LB> number ( number | INFINITY ) <RB>

literal = ( boolean | string | keyword | number )
string = <'"'>  #'[^"]*' <'"'>
boolean = ( TRUE | FALSE )
keyword = #'^:[A-Za-z0-9\:\*\-\_\.]+'
number = ( float | integer )
float = #'[-]?[0-9]+\.[0-9]+'
integer = #'[-]?[0-9]+'
natural = #'[0-9]+'

FALSE = <'false'>
INFINITY = <':infinity'>
LVAR = <'lvar'>
TRUE = <'true'>

LB = <'['>
RB = <']'>
LP = <'('>
RP = <')'>
